"""Built-in model definitions and runtime settings."""

from copy import deepcopy
from pathlib import Path

SAVE_MEMORY = False

_MODEL_CONFIGS = {'cldm_v21': {'target': 'ISM_diffusion.cldm.ControlLDM',
              'params': {'linear_start': 0.00085,
                         'linear_end': 0.012,
                         'num_timesteps_cond': 1,
                         'log_every_t': 200,
                         'timesteps': 1000,
                         'first_stage_key': 'jpg',
                         'cond_stage_key': 'txt',
                         'control_key': 'hint',
                         'image_size': 64,
                         'channels': 4,
                         'cond_stage_trainable': False,
                         'conditioning_key': 'crossattn',
                         'monitor': 'val/loss_simple_ema',
                         'scale_factor': 0.18215,
                         'use_ema': False,
                         'only_mid_control': False,
                         'control_stage_config': {'target': 'ISM_diffusion.cldm.ControlNet',
                                                  'params': {'use_checkpoint': True,
                                                             'image_size': 32,
                                                             'in_channels': 4,
                                                             'hint_channels': 1,
                                                             'model_channels': 320,
                                                             'attention_resolutions': [4, 2, 1],
                                                             'num_res_blocks': 2,
                                                             'channel_mult': [1, 2, 4, 4],
                                                             'num_head_channels': 64,
                                                             'use_spatial_transformer': True,
                                                             'use_linear_in_transformer': True,
                                                             'transformer_depth': 1,
                                                             'context_dim': 1024,
                                                             'legacy': False}},
                         'unet_config': {'target': 'ISM_diffusion.cldm.ControlledUnetModel',
                                         'params': {'use_checkpoint': True,
                                                    'image_size': 32,
                                                    'in_channels': 4,
                                                    'out_channels': 4,
                                                    'model_channels': 320,
                                                    'attention_resolutions': [4, 2, 1],
                                                    'num_res_blocks': 2,
                                                    'channel_mult': [1, 2, 4, 4],
                                                    'num_head_channels': 64,
                                                    'use_spatial_transformer': True,
                                                    'use_linear_in_transformer': True,
                                                    'transformer_depth': 1,
                                                    'context_dim': 1024,
                                                    'legacy': False}},
                         'first_stage_config': {'target': 'ISM_diffusion.models.autoencoder.AutoencoderKL',
                                                'params': {'embed_dim': 4,
                                                           'monitor': 'val/rec_loss',
                                                           'ddconfig': {'attn_type': 'vanilla-xformers',
                                                                        'double_z': True,
                                                                        'z_channels': 4,
                                                                        'resolution': 256,
                                                                        'in_channels': 3,
                                                                        'out_ch': 3,
                                                                        'ch': 128,
                                                                        'ch_mult': [1, 2, 4, 4],
                                                                        'num_res_blocks': 2,
                                                                        'attn_resolutions': [],
                                                                        'dropout': 0.0},
                                                           'lossconfig': {'target': 'torch.nn.Identity'}}},
                         'cond_stage_config': {'target': 'torch.nn.Identity'}}},
 'cldm_v15': {'target': 'ISM_diffusion.cldm.ControlLDM',
              'params': {'linear_start': 0.00085,
                         'linear_end': 0.012,
                         'num_timesteps_cond': 1,
                         'log_every_t': 200,
                         'timesteps': 1000,
                         'first_stage_key': 'jpg',
                         'cond_stage_key': 'txt',
                         'control_key': 'hint',
                         'image_size': 64,
                         'channels': 4,
                         'cond_stage_trainable': False,
                         'conditioning_key': 'crossattn',
                         'monitor': 'val/loss_simple_ema',
                         'scale_factor': 0.18215,
                         'use_ema': False,
                         'only_mid_control': False,
                         'control_stage_config': {'target': 'ISM_diffusion.cldm.ControlNet',
                                                  'params': {'image_size': 32,
                                                             'in_channels': 4,
                                                             'hint_channels': 3,
                                                             'model_channels': 320,
                                                             'attention_resolutions': [4, 2, 1],
                                                             'num_res_blocks': 2,
                                                             'channel_mult': [1, 2, 4, 4],
                                                             'num_heads': 8,
                                                             'use_spatial_transformer': True,
                                                             'transformer_depth': 1,
                                                             'context_dim': 768,
                                                             'use_checkpoint': True,
                                                             'legacy': False}},
                         'unet_config': {'target': 'ISM_diffusion.cldm.ControlledUnetModel',
                                         'params': {'image_size': 32,
                                                    'in_channels': 4,
                                                    'out_channels': 4,
                                                    'model_channels': 320,
                                                    'attention_resolutions': [4, 2, 1],
                                                    'num_res_blocks': 2,
                                                    'channel_mult': [1, 2, 4, 4],
                                                    'num_heads': 8,
                                                    'use_spatial_transformer': True,
                                                    'transformer_depth': 1,
                                                    'context_dim': 768,
                                                    'use_checkpoint': True,
                                                    'legacy': False}},
                         'first_stage_config': {'target': 'ISM_diffusion.models.autoencoder.AutoencoderKL',
                                                'params': {'embed_dim': 4,
                                                           'monitor': 'val/rec_loss',
                                                           'ddconfig': {'double_z': True,
                                                                        'z_channels': 4,
                                                                        'resolution': 256,
                                                                        'in_channels': 3,
                                                                        'out_ch': 3,
                                                                        'ch': 128,
                                                                        'ch_mult': [1, 2, 4, 4],
                                                                        'num_res_blocks': 2,
                                                                        'attn_resolutions': [],
                                                                        'dropout': 0.0},
                                                           'lossconfig': {'target': 'torch.nn.Identity'}}},
                         'cond_stage_config': {'target': 'ISM_diffusion.modules.encoders.modules.FrozenCLIPEmbedder'}}}}


def get_model_config(name="cldm_v21"):
    """Return an independent built-in definition or load an explicit YAML file."""
    if str(name) in _MODEL_CONFIGS:
        return deepcopy(_MODEL_CONFIGS[str(name)])
    import yaml

    with Path(name).open(encoding="utf-8") as stream:
        return yaml.safe_load(stream)["model"]
